# Este é um fluxo de trabalho básico para ajudar você a começar a usar o Actions
Em
nome    :
CI
Em
# Controle quando o fluxo de trabalho será executado
em 
:
Em
  # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo além de outras ações para construir,
          echo teste e implante seu projeto.
Em
